### ISSUE TITLE
boa安装成功了吗

### ISSUE THREAD

**Issue by briteming** [txthinking/jinbe#1]
hi。
在我的vps上。
[root@racknerd-7b97d8 gopath]# which nami
/root/go/gopath/bin/nami
[root@racknerd-7b97d8 gopath]# 
[root@racknerd-7b97d8 gopath]# 
[root@racknerd-7b97d8 gopath]# cd ~
[root@racknerd-7b97d8 ~]# nami install github.com/brook-community/boa
+-------------------+--------------------------------+
| Package           | github.com/brook-community/boa |
|                   |                                |
| Installed Version | v20210214                      |
| Installed Files   | boa                            |
+-------------------+--------------------------------+
[root@racknerd-7b97d8 ~]# which boa
/usr/bin/which: no boa in (/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/go/bin:/root/go/gopath/bin:/usr/local/nginx/sbin:/root/bin)
[root@racknerd-7b97d8 ~]#

boa的可执行文件在哪里？

**Comment by briteming** [comment]
哦，
[root@racknerd-7b97d8 ~]# find / -name boa
/root/.nami/bin/boa
[root@racknerd-7b97d8 ~]# 

哦，原来在那里。

**Comment by txthinking** [comment]
你的nami是非主流方式安装的，用主页命令安装的话会自动加入path

**Comment by luckypoem** [comment]
如果要取消开机自启动，该怎么做？

**Comment by luckypoem** [comment]
boa remove <id>
