### ISSUE TITLE
exit status 1，无法使用

### ISSUE THREAD

**Issue by yanstu** [txthinking/jinbe#11]
jinbe后面加什么命令都不行，都会出现exit status 1

![488f166aae3f0a9ce886d9369a996ea](https://user-images.githubusercontent.com/47344296/234165291-cebb8a00-68fc-4123-97a7-86a70b727fc7.png)

**Comment by txthinking** [comment]
crontab
是不是系统没有

**Comment by yanstu** [comment]
有的
![image](https://user-images.githubusercontent.com/47344296/234455579-5626bb8c-b03f-4505-b509-dc2e7c5ed34f.png)

**Comment by txthinking** [comment]
试试 v20230426 应该会输出错误原因

**Comment by txthinking** [comment]
什么原因

**Comment by yanstu** [comment]
不知道，我的测试机可以用，服务器不能用，就想着不折腾了
![image](https://user-images.githubusercontent.com/47344296/235329509-58839cb3-352d-4cd4-abf3-ca02c783fdeb.png)
![image](https://user-images.githubusercontent.com/47344296/235329532-343071d6-e7da-4ed1-b24c-d540494422db.png)
