### ISSUE TITLE
jinbe not upgraded on last version, and not working for me

### ISSUE THREAD

**Issue by recoilme** [txthinking/jinbe#6]
Hello
I dont may upgarde jinbe on last version, log:

nami remove jinbe
 - OK
nami install jinbe:
| Installed Version | v20220404 |

jinbe version
v20210401

Looks like not last version. I try run with this version brook but it not work:

 jinbe joker brook server --listen :8081 --password some

jinbe list
0	 /root/.nami/bin/joker /root/.nami/bin/brook server --listen :8081 --password some

but it not work, without jinbe - joker/brook work. Im on root, linux

**Comment by txthinking** [comment]
That's a small bug, I forgot change the version https://github.com/txthinking/jinbe/blob/master/main.js#L34

**Comment by txthinking** [comment]
jinbe added boot start command only, not run it now

**Comment by txthinking** [comment]
You may want 
```
joker brook server --listen :8081 --password some
jinbe joker brook server --listen :8081 --password some
```

**Comment by recoilme** [comment]
Thank you!
